version: '3.7'

services:
  colors-blue:
    image: myregistry.local:5000/apisample:latest
    networks:
      - inbound
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - "traefik.http.routers.colors-blue.priority=100"
        - "traefik.http.routers.colors-blue.rule=Path(`/`)"
        - "traefik.http.routers.colors-blue.rule=Host(`apisample.localhost`)"
        - "traefik.http.routers.colors-blue.service=colors-blue"
        - "traefik.http.services.colors-blue.loadbalancer.server.port=8080"
        - "traefik.docker.network=inbound"
networks:
  inbound:
   external: true
